---
abstract: 'University of Granada proposal for YAPC::EU 2015'
author:
  - 'UGR + Barcelona.pm + Madrid.pm'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132140'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAPC-Europe-UGR
no_index:
  directory:
    - t
    - inc
requires:
  App::pod2pdf: 0
  Test::More: 0
  Test::Pod: 0
  Test::PureASCII: 0
  Test::Spelling: 0
  experimental: 0
  version: 0
version: v0.9.0
